name: Pep8 Check

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  pep8-check:
    runs-on: ubuntu-latest
    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3